version: "2"
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ca:latest
    networks:
      - jenkins
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HOST=tcp://socat:2375
    depends_on:
      - socat
  socat:
    container_name: socat
    image: socat-ca:latest
    networks:
      - jenkins
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "2375"
  postgres1:
    container_name: postgres1
    image: postgres-ca:latest
    networks:
      - jenkins
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
  sonarqube:
    container_name: sonarqube
    image: sonarqube-ca:latest
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres1:5432/sonar"
    depends_on:
      - postgres1

networks:
  jenkins:
